// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindSong(arg1) {
  return window['go']['main']['App']['FindSong'](arg1);
}

export function InCache(arg1) {
  return window['go']['main']['App']['InCache'](arg1);
}

export function JSLog(arg1, arg2) {
  window['go']['main']['App']['JSLog'](arg1, arg2);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function Sleep() {
  return window['go']['main']['App']['Sleep']();
}

export function SongDownloaded(arg1) {
  return window['go']['main']['App']['SongDownloaded'](arg1);
}

export function GetAllSongs() {
  return window['go']['main']['App']['GetAllSongs']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Parse(arg1) {
  return window['go']['main']['App']['Parse'](arg1);
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function UpdateSong(arg1) {
  window['go']['main']['App']['UpdateSong'](arg1);
}

export function SearchSaved(arg1) {
  return window['go']['main']['App']['SearchSaved'](arg1);
}
