// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {settings} from '../models';
import {global_state} from '../models';

export function FindSong(arg1:string):Promise<db.Song>;

export function InCache(arg1:string):Promise<db.Song>;

export function JSLog(arg1:string,arg2:string):void;

export function Settings():Promise<settings.SettingsStruct>;

export function Search(arg1:string):Promise<Array<db.Song>>;

export function Sleep():Promise<string>;

export function SongDownloaded(arg1:string):Promise<boolean>;

export function GetAllSongs():Promise<Array<db.Song>>;

export function GetState():Promise<global_state.Statemap>;

export function Greet(arg1:string):Promise<string>;

export function Parse(arg1:string):Promise<string>;

export function Save(arg1:string):Promise<boolean>;

export function UpdateSong(arg1:db.Song):void;

export function SearchSaved(arg1:string):Promise<Array<db.Song>>;
